#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Sep 14 16:23:38 CDT 2026
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim lab_tb_time_impl -key {Post-Implementation:sim_1:Timing:lab_tb} -tclbatch lab_tb.tcl -log simulate.log"
xsim lab_tb_time_impl -key {Post-Implementation:sim_1:Timing:lab_tb} -tclbatch lab_tb.tcl -log simulate.log

